### ISSUE TITLE
generating  figure has error

### ISSUE THREAD

**Issue by yangfeizZZ** [XiaoTaoWang/NeoLoopFinder#38]
Hi:
I plot the figure following your Github,it has an error.

My code:
from neoloop.visualize.core import *
import cooler
clr = cooler.Cooler("M2_5000.cool")
assembly = "C2      translocation,7,152075000,-,21,11095000,+       7,152110000     21,11055000"
vis = Triangle(clr, assembly, n_rows=3, figsize=(7, 4.2), track_partition=[5, 0.4, 0.5], correct='sweight')
vis.matrix_plot(vmin=0,vmax=0.015)
vis.plot_chromosome_bounds(linewidth=2.5)
vis.plot_loops('M1.neo-loop_0.8.txt', face_color='none', marker_size=40, cluster=True)
vis.plot_genes(filter_=['PRIM2',"TP53"],label_aligns={'PRI':'right'} ,fontsize=9)
vis.plot_chromosome_bar(name_size=10, coord_size=4.8)
vis.outfig('test.pdf')

The error :
INFO:pyensembl.sequence_data:Loaded sequence dictionary from /home/yangfei/.cache/pyensembl/GRCh38/ensembl97/Homo_sapiens.GRCh38.cdna.all.fa.gz.pickle
INFO:pyensembl.sequence_data:Loaded sequence dictionary from /home/yangfei/.cache/pyensembl/GRCh38/ensembl97/Homo_sapiens.GRCh38.ncrna.fa.gz.pickle
INFO:pyensembl.sequence_data:Loaded sequence dictionary from /home/yangfei/.cache/pyensembl/GRCh38/ensembl97/Homo_sapiens.GRCh38.pep.all.fa.gz.pickle
Traceback (most recent call last):
  File "plot.py", line 11, in <module>
    vis.plot_genes(filter_=['PRIM2',"TP53"],label_aligns={'PRI':'right'} ,fontsize=9)
  File "/home/yangfei/.conda/envs/neoloop/lib/python3.7/site-packages/neoloop/visualize/core.py", line 484, in plot_genes
    style=style, global_max_row=global_max_row)
  File "/home/yangfei/.conda/envs/neoloop/lib/python3.7/site-packages/neoloop/visualize/bed.py", line 321, in __init__
    self.interval_tree, min_score, max_score = self._process_bed()
  File "/home/yangfei/.conda/envs/neoloop/lib/python3.7/site-packages/neoloop/visualize/bed.py", line 326, in _process_bed
    bed_file_h = ReadBed(self.properties['file_'])
  File "/home/yangfei/.conda/envs/neoloop/lib/python3.7/site-packages/coolbox/utilities/bed.py", line 122, in __init__
    fields = self.get_no_comment_line()
  File "/home/yangfei/.conda/envs/neoloop/lib/python3.7/site-packages/coolbox/utilities/bed.py", line 154, in get_no_comment_line
    line = next(self.file_handle)
StopIteration

**Comment by zzhoujialu** [comment]
Hi, I met the same error. May I ask you how to solve it?

**Comment by flysheeeep** [comment]
U can check whether the inputted genes' coordinates in certain ensembl release are in the assembly region
