### ISSUE TITLE
neoloop-caller error 

### ISSUE THREAD

**Issue by ldyyzhangh** [XiaoTaoWang/NeoLoopFinder#40]
Hi Xiaotao,
I installed NeoLoopFinder and all the dependencies on 2022-11-11, when i run neoloop-caller,error occur:
**# ARGUMENT LIST:
# Output Path = sample_loops.txt
# Cache Folder = CACHEFOLDER
# SV assembly = sample.assemblies.txt
# Cooler List = ['output.mcool::/resolutions/5000']
# Extended Genomic Span = 3000000bp
# Balance Type = ICE
# Probability threshold = 0.9
# No pooling = False
# Minimum marginal peaks = 2
# Number of Processes = 1
# Log file name = neoloop.log
Traceback (most recent call last):
  File "/home/data/vip02/miniconda3/envs/neoloop/bin/neoloop-caller", line 131, in run
    models_by_res = download_peakachu_models(cachefolder, cools)
  File "/home/data/vip02/miniconda3/envs/neoloop/bin/neoloop-caller", line 258, in download_peakachu_models
    subprocess.check_call(' '.join(command), shell=True)
  File "/home/data/vip02/miniconda3/envs/neoloop/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'wget -O /home/data/vip02/HIC/neoloops/CACHEFOLDER/peakachu_v2.res5000.depth50000000.pkl -L http://3dgenome.fsm.northwestern.edu/peakachu/high-confidence.50million.5kb.w6.pkl' returned non-zero exit status 8.**

Then I download the ".pkl" files from "https://github.com/XiaoTaoWang/NeoLoopFinder/tree/master/neoloop/data" and put the mode into "CACHEFOLDER" ,new error occur:

**# ARGUMENT LIST:
# Output Path = sample_loops.txt
# Cache Folder = CACHEFOLDER
# SV assembly = sample.assemblies.txt
# Cooler List = ['output.mcool::/resolutions/5000']
# Extended Genomic Span = 3000000bp
# Balance Type = ICE
# Probability threshold = 0.9
# No pooling = True
# Minimum marginal peaks = 2
# Number of Processes = 1
# Log file name = neoloop.log
root                      INFO    @ 11/11/22 21:34:03: Load assembled SVs
root                      INFO    @ 11/11/22 21:34:03: Current resolution: 5000
root                      INFO    @ 11/11/22 21:34:03: Calculate the global average contact frequencies at each genomic distance ...
root                      INFO    @ 11/11/22 21:36:20: Done
Traceback (most recent call last):
  File "/home/data/vip02/miniconda3/envs/neoloop/bin/neoloop-caller", line 157, in run
    results = Parallel(n_jobs=args.nproc, verbose=10)(delayed(pipeline)(*i) for i in Params)
  File "/home/data/vip02/miniconda3/envs/neoloop/lib/python3.10/site-packages/joblib/parallel.py", line 1046, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/data/vip02/miniconda3/envs/neoloop/lib/python3.10/site-packages/joblib/parallel.py", line 861, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/data/vip02/miniconda3/envs/neoloop/lib/python3.10/site-packages/joblib/parallel.py", line 779, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/data/vip02/miniconda3/envs/neoloop/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/home/data/vip02/miniconda3/envs/neoloop/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/home/data/vip02/miniconda3/envs/neoloop/lib/python3.10/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/home/data/vip02/miniconda3/envs/neoloop/lib/python3.10/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/data/vip02/miniconda3/envs/neoloop/bin/neoloop-caller", line 202, in pipeline
    core.load_models(models_by_res[fu.res])
  File "/home/data/vip02/miniconda3/envs/neoloop/lib/python3.10/site-packages/neoloop/callers.py", line 577, in load_models
    self.w = int((np.sqrt(self.model.feature_importances_.size) - 1) / 2)
AttributeError: 'dict' object has no attribute 'feature_importances_'**

I don't know what happens?

**Comment by XiaoTaoWang** [comment]
Hi, there were some issues on our server. We have fixed them, can you try again?

Xiaotao

**Comment by ldyyzhangh** [comment]
It works well. 
Thanks!
