### ISSUE TITLE
segment-cnv error 

### ISSUE THREAD

**Issue by abhijitcbio** [XiaoTaoWang/NeoLoopFinder#55]
Hi, I am trying to run the segment-cnv code on the cnv-profile file, but getting the following error -
```
root                      INFO    @ 08/04/23 11:40:02:
# ARGUMENT LIST:
# CNV Profile = Cancer_CNV_profile_50Kb.bedGraph
# Number of States = None
# CBS P-value Cutoff = 1e-05
# Maximum HMM-CBS distance = 4
# Minimum Copy Number difference = 0.4
# Minimum Segment Size = 3
# Ploidy = 2
# Bin Size = 50000
# Output Path = Cancer_CNV_seg_50Kb.bedGraph
# Number of Processes = 1
# Log file name = cnv-seg.log
numexpr.utils             INFO    @ 08/04/23 11:40:04: Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
root                      INFO    @ 08/04/23 11:40:04: Loading CNV profile ...
Traceback (most recent call last):
  File "/mnt/BioHome/abhijit/miniconda3/bin/segment-cnv", line 115, in run
    p=args.cbs_pvalue
  File "/home/abhijit/miniconda3/lib/python3.7/site-packages/neoloop/cnv/segcnv.py", line 156, in segment
    training_seqs, gmm = self.get_states(maxdist=10)
  File "/home/abhijit/miniconda3/lib/python3.7/site-packages/neoloop/cnv/segcnv.py", line 336, in get_states
    gmm.fit(X)
  File "/home/abhijit/.local/lib/python3.7/site-packages/sklearn/mixture/_base.py", line 198, in fit
    self.fit_predict(X, y)
  File "/home/abhijit/.local/lib/python3.7/site-packages/sklearn/mixture/_base.py", line 251, in fit_predict
    self._initialize_parameters(X, random_state)
  File "/home/abhijit/.local/lib/python3.7/site-packages/sklearn/mixture/_base.py", line 155, in _initialize_parameters
    "Unimplemented initialization method '%s'" % self.init_params
ValueError: Unimplemented initialization method 'k-means++'
```
Your help will be much appreciated.

**Comment by XiaoTaoWang** [comment]
Which scikit-learn version did you use?

**Comment by abhijitcbio** [comment]
I am using the 1.0.2 version within python 3.7
```
>>> import sklearn
>>> print(sklearn.__version__)
1.0.2
```
I tried to upgrade it to 1.1.2 as suggested but got this error 
```
pip install -U scikit-learn==1.1.2
ERROR: Could not find a version that satisfies the requirement scikit-learn==1.7.3 (from versions: 0.9, 0.10, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.14, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.17, 0.17.1, 0.18, 0.18.1, 0.18.2, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.20.4, 0.21.0, 0.21.1, 0.21.2, 0.21.3, 0.22, 0.22.1, 0.22.2, 0.22.2.post1, 0.23.0, 0.23.1, 0.23.2, 0.24.0, 0.24.1, 0.24.2, 1.0, 1.0.1, 1.0.2)
ERROR: No matching distribution found for scikit-learn==1.1.2
```
