### ISSUE TITLE
what 's the version of pomegranate?

### ISSUE THREAD

**Issue by HanwenZhu98** [XiaoTaoWang/NeoLoopFinder#56]
I meet the errror  like this:
Traceback (most recent call last):
  File "/cluster/home/Kangwen/anaconda3/envs/Hic/bin/segment-cnv", line 111, in run
    work.segment(
  File "/cluster/home/Kangwen/anaconda3/envs/Hic/lib/python3.10/site-packages/neoloop/cnv/segcnv.py", line 167, in segment
    model = HiddenMarkovModel.from_samples(
NameError: name 'HiddenMarkovModel' is not defined

I check it, and find that the error is in the script segcnv at  "from pomegranate import NormalDistribution, HiddenMarkovModel"

So,can u tell me how to solve this problem?

**Comment by XiaoTaoWang** [comment]
It seems that the API has undergone dramatic changes since pomegranate v1.0.0. Can you downgrade your pomegranate to v0.14.8 and try again?

**Comment by hmgene** [comment]
I have the same issue:
cannot find the version but only v1.00 available in conda
```
conda search pomegranate
Loading channels: done
# Name                       Version           Build  Channel             
pomegranate                    1.0.0    pyhd8ed1ab_0  conda-forge         
pomegranate                    1.0.0    pyhd8ed1ab_1  conda-forge    
```

**Comment by XiaoTaoWang** [comment]
Did you tried using pip to install pomegranate version 0.14.8?

**Comment by hmgene** [comment]
It is not available on Mac mamba. I have modified your code to adopt the new Pomegranate insteadThank you Sent from my iPhoneOn Dec 10, 2024, at 21:33, Xiaotao Wang ***@***.***> wrote:﻿
Did you tried using pip to install pomegranate version 0.14.8?

**Comment by mnfrandre** [comment]
Hi all,
Please try pomegranate version 0.15.0. Works for me!

**Comment by AndreaEsp** [comment]
> It is not available on Mac mamba. I have modified your code to adopt the new Pomegranate insteadThank you Sent from my iPhoneOn Dec 10, 2024, at 21:33, Xiaotao Wang ***@***.***> wrote:﻿
> Did you tried using pip to install pomegranate version 0.14.8?
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

Hi @hmgene, can you explain how you modified the code to be used with the new version of pomegranate?
