### ISSUE TITLE
neoloop-caller running error

### ISSUE THREAD

**Issue by xunchen85** [XiaoTaoWang/NeoLoopFinder#57]
Dear XiaoTao,

I was able to use it to generate the assemblie file, although I got the following errors when I called the neo-loops. I have attached the log files below. I am wondering if you could kindly help!

Best wishes,
Xun

##### log file
# ARGUMENT LIST:
# Output Path = Tong_inter_30.2.eagle.neoloops.txt
# Cache Folder = .cache
# SV assembly = Tong_inter_30.2.eagle.assemblies.txt
# Cooler List = ['Tong_inter_30.2.mcool::resolutions/50000', 'Tong_inter_30.2.mcool::resolutions/10000', 'Tong_inter_30.2.mcool::resolutions/5000']
# Extended Genomic Span = 3000000bp
# Balance Type = CNV
# Probability threshold = 0.95
# No pooling = False
# Minimum marginal peaks = 2
# Number of Processes = 4
# Log file name = Tong_inter_30.2.eagle.neoloops.log
numexpr.utils             INFO    @ 10/12/23 22:28:42: Note: NumExpr detected 40 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
numexpr.utils             INFO    @ 10/12/23 22:28:42: NumExpr defaulting to 8 threads.
root                      INFO    @ 10/12/23 22:28:52: Load assembled SVs
root                      INFO    @ 10/12/23 22:28:52: Current resolution: 50000
root                      INFO    @ 10/12/23 22:28:52: Calculate the global average contact frequencies at each genomic distance ...
root                      INFO    @ 10/12/23 22:28:57: Done
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/xchen85/ENV3.8_fanc/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 428, in _process_worker
    r = call_item()
  File "/home/xchen85/ENV3.8_fanc/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 275, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/xchen85/ENV3.8_fanc/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
  File "/home/xchen85/ENV3.8_fanc/lib/python3.8/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/home/xchen85/ENV3.8_fanc/lib/python3.8/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/xchen85/ENV3.8_fanc/bin/neoloop-caller", line 202, in pipeline
    core.load_models(models_by_res[fu.res])
  File "/home/xchen85/ENV3.8_fanc/lib/python3.8/site-packages/neoloop/callers.py", line 576, in load_models
    self.model = joblib.load(model_fil_path)
  File "/home/xchen85/ENV3.8_fanc/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/xchen85/ENV3.8_fanc/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.10/lib/python3.8/pickle.py", line 1210, in load
    raise EOFError
EOFError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xchen85/ENV3.8_fanc/bin/neoloop-caller", line 157, in run
    results = Parallel(n_jobs=args.nproc, verbose=10)(delayed(pipeline)(*i) for i in Params)
  File "/home/xchen85/ENV3.8_fanc/lib/python3.8/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/home/xchen85/ENV3.8_fanc/lib/python3.8/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/xchen85/ENV3.8_fanc/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.10/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.10/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
EOFError

**Comment by xunchen85** [comment]
I have resolved it by changing to use another computer.

Xun
