### ISSUE TITLE
‘module 'numpy' has no attribute 'typeDict'’ while searchSVbyGene

### ISSUE THREAD

**Issue by Wong718** [XiaoTaoWang/NeoLoopFinder#69]

**Comment by Wong718** [comment]
Hello, Xiaotao, It's a wonderful tool for neoloop detection.
Here is an issue when applying the searchSVbyGene step.

The code I wrote:
```
searchSVbyGene -L HS_E_15_ESCC.neo-loops.txt -G TP53
```

The error output:
```
INFO:pyensembl.database:Creating database: /dshare/home/wangzj/.cache/pyensembl/GRCh38/ensembl93/Homo_sapiens.GRCh38.93.gtf.db
INFO:pyensembl.database:Reading GTF from /dshare/home/wangzj/.cache/pyensembl/GRCh38/ensembl93/Homo_sapiens.GRCh38.93.gtf.gz
INFO:root:Extracted GTF attributes: ['gene_id', 'gene_version', 'gene_name', 'gene_source', 'gene_biotype', 'transcript_id', 'transcript_version', 'transcript_name', 'transcript_source', 'transcript_biotype', 'tag', 'transcript_support_level', 'exon_number', 'exon_id', 'exon_version', 'protein_id', 'protein_version', 'ccds_id']
Traceback (most recent call last):
  File "/dshare/home/wangzj/env_set/miniconda3/envs/neoloop/bin/searchSVbyGene", line 87, in <module>
    run()
  File "/dshare/home/wangzj/env_set/miniconda3/envs/neoloop/bin/searchSVbyGene", line 53, in run
    db.index()
  File "/dshare/home/wangzj/env_set/miniconda3/envs/neoloop/lib/python3.10/site-packages/pyensembl/genome.py", line 280, in index
    self.db.connect_or_create(overwrite=overwrite)
  File "/dshare/home/wangzj/env_set/miniconda3/envs/neoloop/lib/python3.10/site-packages/pyensembl/database.py", line 286, in connect_or_create
    return self.create(overwrite=overwrite)
  File "/dshare/home/wangzj/env_set/miniconda3/envs/neoloop/lib/python3.10/site-packages/pyensembl/database.py", line 239, in create
    self._connection = datacache.db_from_dataframes_with_absolute_path(
  File "/dshare/home/wangzj/env_set/miniconda3/envs/neoloop/lib/python3.10/site-packages/datacache/database_helpers.py", line 176, in db_from_dataframes_with_absolute_path
    tables = build_tables(
  File "/dshare/home/wangzj/env_set/miniconda3/envs/neoloop/lib/python3.10/site-packages/datacache/database_helpers.py", line 136, in build_tables
    table = DatabaseTable.from_dataframe(
  File "/dshare/home/wangzj/env_set/miniconda3/envs/neoloop/lib/python3.10/site-packages/datacache/database_table.py", line 56, in from_dataframe
    column_db_type = db_type(values.dtype)
  File "/dshare/home/wangzj/env_set/miniconda3/envs/neoloop/lib/python3.10/site-packages/datacache/database_types.py", line 92, in db_type
    for type_name in _candidate_type_names(python_type_representation):
  File "/dshare/home/wangzj/env_set/miniconda3/envs/neoloop/lib/python3.10/site-packages/datacache/database_types.py", line 64, in _candidate_type_names
    if python_type_representation in np.typeDict:
  File "/dshare/home/wangzj/env_set/miniconda3/envs/neoloop/lib/python3.10/site-packages/numpy/__init__.py", line 333, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'typeDict'. Did you mean: 'sctypeDict'?
```

Can you help me fix this issue? Thanks a lot.

**Comment by Wong718** [comment]
When I downgraded the version of numpy to 1.23.5, a new error was raised.
```
INFO:pyensembl.database:Creating database: /dshare/home/wangzj/.cache/pyensembl/GRCh38/ensembl93/Homo_sapiens.GRCh38.93.gtf.db
INFO:pyensembl.database:Reading GTF from /dshare/home/wangzj/.cache/pyensembl/GRCh38/ensembl93/Homo_sapiens.GRCh38.93.gtf.gz
INFO:root:Extracted GTF attributes: ['gene_id', 'gene_version', 'gene_name', 'gene_source', 'gene_biotype', 'transcript_id', 'transcript_version', 'transcript_name', 'transcript_source', 'transcript_biotype', 'tag', 'transcript_support_level', 'exon_number', 'exon_id', 'exon_version', 'protein_id', 'protein_version', 'ccds_id']
Traceback (most recent call last):
  File "/dshare/home/wangzj/env_set/miniconda3/envs/neoloop/bin/searchSVbyGene", line 87, in <module>
    run()
  File "/dshare/home/wangzj/env_set/miniconda3/envs/neoloop/bin/searchSVbyGene", line 53, in run
    db.index()
  File "/dshare/home/wangzj/env_set/miniconda3/envs/neoloop/lib/python3.10/site-packages/pyensembl/genome.py", line 280, in index
    self.db.connect_or_create(overwrite=overwrite)
  File "/dshare/home/wangzj/env_set/miniconda3/envs/neoloop/lib/python3.10/site-packages/pyensembl/database.py", line 286, in connect_or_create
    return self.create(overwrite=overwrite)
  File "/dshare/home/wangzj/env_set/miniconda3/envs/neoloop/lib/python3.10/site-packages/pyensembl/database.py", line 239, in create
    self._connection = datacache.db_from_dataframes_with_absolute_path(
  File "/dshare/home/wangzj/env_set/miniconda3/envs/neoloop/lib/python3.10/site-packages/datacache/database_helpers.py", line 176, in db_from_dataframes_with_absolute_path
    tables = build_tables(
  File "/dshare/home/wangzj/env_set/miniconda3/envs/neoloop/lib/python3.10/site-packages/datacache/database_helpers.py", line 136, in build_tables
    table = DatabaseTable.from_dataframe(
  File "/dshare/home/wangzj/env_set/miniconda3/envs/neoloop/lib/python3.10/site-packages/datacache/database_table.py", line 56, in from_dataframe
    column_db_type = db_type(values.dtype)
  File "/dshare/home/wangzj/env_set/miniconda3/envs/neoloop/lib/python3.10/site-packages/datacache/database_types.py", line 96, in db_type
    raise ValueError("Failed to find sqlite3 column type for %s" % (
ValueError: Failed to find sqlite3 column type for category
```

**Comment by CheZhaoxuan** [comment]
From the perspective of the error stack, when you run the `searchSVbyGene` function (from the neoloop package), the program attempts to load the genomic annotation data (GTF file) using pyensembl and create an SQLite database to accelerate the query. However, when creating the database, the db_type function of the datacache module fails to find the corresponding SQLite column type for the category data type in the Pandas data frame, resulting in the following error being thrown:

`ValueError: Failed to find sqlite3 column type for category`

Change the version to python==3.8; Datacache = = 1.4.0; Pylint = = 2.17.2; pandas==1.5.3 might work.
